---
# Location where configuration files will be stored.
config_dir: '~'

# Docker image versions
docker_image_versions:
  nginx_proxy: '1.30-alpine'
  prometheus: 'v3.13.1'
  grafana: '13.1.1'
  blackbox_exporter: 'v0.28.0'
  speedtest_exporter: 'v3.5.4'
  node_exporter: 'v1.12.1'
  pihole: '2026.07.2'
  pihole_exporter: 'v1.2.0'
  wireguard: '15'
  homebridge: '2026-07-20'
  php_apache: '8.5.8-apache'
  starlink_exporter: 'v0.0.5'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'home.local'
domain_pihole: 'pihole'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local
domain_wireguard: 'wireguard'    # to access wireguard via: http://wireguard.home.local
domain_homebridge: 'homebridge'  # to access homebridge via: http://homebridge.home.local

# Pi-hole configuration.
pihole_enable: true
pihole_hostname: pihole
pihole_timezone: America/Chicago
pihole_password: "change-this-password"

wireguard_enable: true
wireguard_host: 'public.hostname.of.your.VPN.server'
wireguard_default_address: 10.8.0.x
wireguard_password: "change-this-password"

# Raspberry monitoring configuration
raspberry_monitoring_enable: false

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "admin"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 30s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;apple.com

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
prometheus_tsdb_retention_time: 90d

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

# Homebridge configuration.
homebridge_enable: false
homebridge_port: 8581
homebridge_bridge_name: "Pi"
homebridge_bridge_mac: "0E:21:A4:C8:F9:7E"  # Change this to a unique MAC (format: XX:XX:XX:XX:XX:XX)
homebridge_pin: "xxx-xx-xxx"  # Change this to a random pin (format: 000-00-000)
homebridge_admin_username: "admin"
homebridge_admin_password: "admin"  # Change this
homebridge_cameras:
  - name: "Pi Cam"
    stream_url: "http://192.168.1.4:8888/stream.mjpg"
    max_width: 1280
    max_height: 720
    max_fps: 10
    max_streams: 2
    vcodec: "h264_v4l2m2m"
