---
- name: Configure Internet Pi.
  hosts: internet_pi
  become: true
  gather_facts: false

  pre_tasks:
    - name: Gather required Ansible facts.
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - min
          - distribution
          - architecture
          - network

    - name: Load configuration (with defaults from example file).
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - example.config.yml
        - config.yml

  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: tasks/handlers.yml

  tasks:
    - name: Set up Internet Monitoring.
      ansible.builtin.import_tasks: tasks/internet-monitoring.yml
      when: monitoring_enable

    - name: Set up Raspberry Pi Monitoring.
      ansible.builtin.import_tasks: tasks/raspberry-monitoring.yml
      when: raspberry_monitoring_enable

    - name: Set up Pi Hole.
      ansible.builtin.import_tasks: tasks/pi-hole.yml
      when: pihole_enable

    - name: Set up wireguard.
      ansible.builtin.import_tasks: tasks/wireguard.yml
      when: wireguard_enable

    - name: Set up Shelly Plug Monitoring.
      ansible.builtin.import_tasks: tasks/shelly-plug.yml
      when: shelly_plug_enable

    - name: Set up Air Gradient Monitoring.
      ansible.builtin.import_tasks: tasks/airgradient.yml
      when: airgradient_enable

    - name: Set up Starlink Monitoring.
      ansible.builtin.import_tasks: tasks/starlink.yml
      when: starlink_enable

    - name: Set up Homebridge.
      ansible.builtin.import_tasks: tasks/homebridge.yml
      when: homebridge_enable
