---
- name: Create textfile collector directory
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    mode: 0755
  become: true

- name: Deploy gpu-temp script
  ansible.builtin.template:
    src: templates/raspberry-monitoring/gpu-temp.sh.j2
    dest: /usr/local/bin/gpu-temp.sh
    mode: 0755
  become: true

- name: Schedule gpu-temp cron job
  ansible.builtin.cron:
    name: gpu_temp_metrics
    job: /usr/local/bin/gpu-temp.sh
    minute: "*/2"
  become: true
